<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 1: Standardized Test Analysis

--- 
# Part 2

Part 2 requires knowledge of Pandas, EDA, data cleaning, and data visualization.

---

*All libraries used should be added here*

In [2]:
# Imports:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [15]:
# Code:
def percent_to_float(percent_string):
    if isinstance(percent_string, float):
        return percent_string
    else:
        float_value = float(percent_string.replace('%', '')) / 100
        return float_value

## Data Import and Cleaning

### Data Import & Cleaning

Import the datasets that you selected for this project and go through the following steps at a minimum. You are welcome to do further cleaning as you feel necessary:
1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.
2. Check for missing values.
3. Check for any obvious issues with the observations (keep in mind the minimum & maximum possible values for each test/subtest).
4. Fix any errors you identified in steps 2-3.
5. Display the data types of each feature.
6. Fix any incorrect data types found in step 5.
    - Fix any individual values preventing other columns from being the appropriate type.
    - If your dataset has a column of percents (ex. '50%', '30.5%', etc.), use the function you wrote in Part 1 (coding challenges, number 3) to convert this to floats! *Hint*: use `.map()` or `.apply()`.
7. Rename Columns.
    - Column names should be all lowercase.
    - Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
    - Column names should be unique and informative.
8. Drop unnecessary rows (if needed).
9. Merge dataframes that can be merged.
10. Perform any additional cleaning that you feel is necessary.
11. Save your cleaned and merged dataframes as csv files.

## 2019 SAT Data Frame

In [5]:
#read SAT dataframe
sat_2019 = pd.read_csv('./data/sat_2019.csv')

#### 1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.

In [6]:
sat_2019.head()

        State Participation Rate  EBRW  Math  Total
0     Alabama                 7%   583   560   1143
1      Alaska                41%   556   541   1097
2     Arizona                31%   569   565   1134
3    Arkansas                 6%   582   559   1141
4  California                63%   534   531   1065

In [7]:
sat_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               53 non-null     object
 1   Participation Rate  53 non-null     object
 2   EBRW                53 non-null     int64
 3   Math                53 non-null     int64
 4   Total               53 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.2+ KB

#### 2. Check for missing values.

In [8]:
sat_2019.isnull().sum()

State                 0
Participation Rate    0
EBRW                  0
Math                  0
Total                 0
dtype: int64

#### 3. Check for any obvious issues with the observations (keep in mind the minimum & maximum possible values for each test/subtest).

In [9]:
#check min
sat_2019['Participation Rate'].min()

'100%'

In [10]:
#check max
sat_2019['Participation Rate'].max()

'—'

In [11]:
sat_2019['Participation Rate'].unique()

array(['7%', '41%', '31%', '6%', '63%', '100%', '94%', '71%', '54%',
       '66%', '3%', '4%', '5%', '99%', '82%', '81%', '9%', '20%', '95%',
       '18%', '79%', '51%', '2%', '19%', '22%', '70%', '—', '68%'],
      dtype=object)

#### 4. Fix any errors you identified in steps 2-3.

In [12]:
#replace '-' value
sat_2019['Participation Rate'] = sat_2019['Participation Rate'].replace('—', np.nan)

#### 5. Display the data types of each feature.

In [13]:
sat_2019.dtypes

State                 object
Participation Rate    object
EBRW                   int64
Math                   int64
Total                  int64
dtype: object

#### 6. Fix any incorrect data types found in step 5. 
   - Fix any individual values preventing other columns from being the appropriate type.
   - If your dataset has a column of percents (ex. '50%', '30.5%', etc.), use the function you wrote in Part 1 (coding challenges, number 3) to convert this to floats! 
   - *Hint*: use `.map()` or `.apply()`.

In [16]:
sat_2019['Participation Rate'] = sat_2019['Participation Rate'].map(percent_to_float)

Column names should be all lowercase.
Column names should not contain spaces (underscores will suffice--this allows for using the df.column_name method to access columns in addition to df['column_name']).
Column names should be unique and informative.#### 7. Rename Columns.
- Column names should be all lowercase.
- Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
- Column names should be unique and informative.

In [17]:
sat_2019.columns = sat_2019.columns.str.lower()
sat_2019.columns = sat_2019.columns.str.replace(' ', '_')
sat_2019.head()

        state  participation_rate  ebrw  math  total
0     Alabama                0.07   583   560   1143
1      Alaska                0.41   556   541   1097
2     Arizona                0.31   569   565   1134
3    Arkansas                0.06   582   559   1141
4  California                0.63   534   531   1065

In [18]:
sat_2019.rename(columns = {'participation_rate' :'participation_rate_2019',
                          'total' : 'total_score_2019'}, inplace = True)

#### 8. Drop unnecessary rows (if needed).

In [19]:
sat_2019 = sat_2019.drop(['ebrw','math'], axis =1)

In [20]:
sat_2019 = sat_2019.dropna()

## 2018 SAT Data Frame

In [21]:
#read ACT dataframe
sat_2018 = pd.read_csv('./data/sat_2018.csv')

#### 1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.

In [22]:
sat_2018.head()

        State Participation  Evidence-Based Reading and Writing  Math  Total
0     Alabama            6%                                 595   571   1166
1      Alaska           43%                                 562   544   1106
2     Arizona           29%                                 577   572   1149
3    Arkansas            5%                                 592   576   1169
4  California           60%                                 540   536   1076

In [23]:
sat_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   State                               51 non-null     object
 1   Participation                       51 non-null     object
 2   Evidence-Based Reading and Writing  51 non-null     int64
 3   Math                                51 non-null     int64
 4   Total                               51 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.1+ KB

#### 2. Check for missing values.

In [24]:
sat_2018.isnull().sum()

State                                 0
Participation                         0
Evidence-Based Reading and Writing    0
Math                                  0
Total                                 0
dtype: int64

#### 3. Check for any obvious issues with the observations (keep in mind the minimum & maximum possible values for each test/subtest).

In [25]:
sat_2018['Participation'].unique()

array(['6%', '43%', '29%', '5%', '60%', '100%', '92%', '56%', '70%',
       '99%', '63%', '3%', '4%', '76%', '80%', '10%', '23%', '96%', '82%',
       '16%', '79%', '52%', '2%', '8%', '18%', '48%', '97%', '55%', '66%',
       '64%', '68%', '69%', '28%'], dtype=object)

#### 4. Fix any errors you identified in steps 2-3.

#### 5. Display the data types of each feature.

In [26]:
sat_2018.dtypes

State                                 object
Participation                         object
Evidence-Based Reading and Writing     int64
Math                                   int64
Total                                  int64
dtype: object

#### 6. Fix any incorrect data types found in step 5. 
   - Fix any individual values preventing other columns from being the appropriate type.
   - If your dataset has a column of percents (ex. '50%', '30.5%', etc.), use the function you wrote in Part 1 (coding challenges, number 3) to convert this to floats! 
   - *Hint*: use `.map()` or `.apply()`.

In [27]:
sat_2018['Participation'] = sat_2018['Participation'].map(percent_to_float)

#### 7. Rename Columns.
- Column names should be all lowercase.
- Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
- Column names should be unique and informative.

In [28]:
sat_2018.columns = sat_2018.columns.str.lower()
sat_2018.columns = sat_2018.columns.str.replace(' ', '_')
sat_2018.head()

        state  participation  evidence-based_reading_and_writing  math  total
0     Alabama           0.06                                 595   571   1166
1      Alaska           0.43                                 562   544   1106
2     Arizona           0.29                                 577   572   1149
3    Arkansas           0.05                                 592   576   1169
4  California           0.60                                 540   536   1076

In [29]:
sat_2018.rename(columns = {'participation' :'participation_rate_2018',
                          'total' : 'total_score_2018'}, inplace=True)

#### 8. Drop unnecessary rows (if needed).

In [30]:
sat_2018 = sat_2018.drop(['evidence-based_reading_and_writing','math'], axis =1)

In [31]:
sat_2018.head()

        state  participation_rate_2018  total_score_2018
0     Alabama                     0.06              1166
1      Alaska                     0.43              1106
2     Arizona                     0.29              1149
3    Arkansas                     0.05              1169
4  California                     0.60              1076

#### 9. Merge dataframes that can be merged.

In [32]:
sat_2018_2019 = pd.merge(sat_2018,sat_2019, on = 'state')
sat_2018_2019.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   state                    51 non-null     object
 1   participation_rate_2018  51 non-null     float64
 2   total_score_2018         51 non-null     int64
 3   participation_rate_2019  51 non-null     float64
 4   total_score_2019         51 non-null     int64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.4+ KB

#### 10. Perform any additional cleaning that you feel is necessary.

#### 11. Save your cleaned and merged dataframes as csv files.

In [87]:
#Code:
sat_2018_2019.to_csv('./data/sat_merged.csv', index = False)