<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 1: Standardized Test Analysis

The objective of this project is to examine the relationship between the percentage of participating SNAP households with children in fiscal years 2018 and 2019 and SAT scores by state in the same years.

The project aims to address the following research questions:

1. How does the percentage of participating SNAP households with children vary across states in fiscal years 2018 and 2019?
2. Is there any correlation between the percentage of participating SNAP households with children and SAT scores by state in fiscal years 2018 and 2019?
3. Can the percentage of participating SNAP households with children be used as a predictor for SAT scores by state?

By analyzing these datasets and exploring the potential relationship between SAT scores and SNAP benefits participation, this project aims to provide insights into any potential associations or patterns that may exist. Such findings could have implications for policymakers and educators in developing strategies to support students from economically disadvantaged backgrounds.

### Contents:
- [Background](#Background)
- [Data Import & Cleaning](#Data-Import-and-Cleaning)
- [Exploratory Data Analysis](#Exploratory-Data-Analysis)
- [Data Visualization](#Visualize-the-Data)
- [Conclusions and Recommendations](#Conclusions-and-Recommendations)

### SAT / ACT
The SAT and ACT are standardized tests that many colleges and universities in the United States require for their admissions process. This score is used along with other materials such as grade point average (GPA) and essay responses to determine whether or not a potential student will be accepted to the university.

The SAT has two sections of the test: Evidence-Based Reading and Writing and Math ([*source*](https://www.princetonreview.com/college/sat-sections)). The ACT has 4 sections: English, Mathematics, Reading, and Science, with an additional optional writing section ([*source*](https://www.act.org/content/act/en/products-and-services/the-act/scores/understanding-your-scores.html)). They have different score ranges, which you can read more about on their websites or additional outside sources (a quick Google search will help you understand the scores for each test):
* [SAT](https://collegereadiness.collegeboard.org/sat)
* [ACT](https://www.act.org/content/act/en.html)

Standardized tests have long been a controversial topic for students, administrators, and legislators. Since the 1940's, an increasing number of colleges have been using scores from sudents' performances on tests like the SAT and the ACT as a measure for college readiness and aptitude ([*source*](https://www.minotdailynews.com/news/local-news/2017/04/a-brief-history-of-the-sat-and-act/)). Supporters of these tests argue that these scores can be used as an objective measure to determine college admittance. Opponents of these tests claim that these tests are not accurate measures of students potential or ability and serve as an inequitable barrier to entry. Lately, more and more schools are opting to drop the SAT/ACT requirement for their Fall 2021 applications ([*read more about this here*](https://www.cnn.com/2020/04/14/us/coronavirus-colleges-sat-act-test-trnd/index.html)).

### SNAP
[SNAP](https://www.fns.usda.gov/snap) stands for the Supplemental Nutrition Assistance Program, which is a federal assistance program in the United States aimed at providing nutrition assistance to low-income individuals and families. It was formerly known as the Food Stamp Program.

SNAP benefits are designed to help [eligible participants](https://www.fns.usda.gov/snap/recipient/eligibility) purchase food and improve their access to nutritious meals. The program provides electronic benefit transfer (EBT) cards that can be used like debit cards to purchase eligible food items at authorized retailers, including grocery stores, supermarkets, and farmers markets.

The eligibility for SNAP benefits is primarily based on household income and size, with specific income thresholds set by the federal government. The program serves a wide range of individuals, including low-wage workers, unemployed individuals, elderly people, and families with children.

SNAP plays a crucial role in reducing food insecurity and improving nutritional outcomes for vulnerable populations. It is administered by the United States Department of Agriculture (USDA), and each state is responsible for implementing the program within its jurisdiction

### Outside Research

Based on your problem statement and your chosen datasets, spend some time doing outside research on state policies or additional information that might be relevant. Summarize your findings below. If you bring in any outside tables or charts, make sure you are explicit about having borrowed them. If you quote any text, make sure that it renders as being quoted. **Make sure that you cite your sources.**

### Coding Challenges

1. Manually calculate mean:

    Write a function that takes in values and returns the mean of the values. Create a list of numbers that you test on your function to check to make sure your function works!
    
    *Note*: Do not use any mean methods built-in to any Python libraries to do this! This should be done without importing any additional libraries.

In [1]:
# Code:
def calculate_mean(numbers):
    total = sum(numbers)
    mean = total / len(numbers)
    return mean

2. Manually calculate standard deviation:

    The formula for standard deviation is below:

    $$\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^n(x_i - \mu)^2}$$

    Where $x_i$ represents each value in the dataset, $\mu$ represents the mean of all values in the dataset and $n$ represents the number of values in the dataset.

    Write a function that takes in values and returns the standard deviation of the values using the formula above. Hint: use the function you wrote above to calculate the mean! Use the list of numbers you created above to test on your function.
    
    *Note*: Do not use any standard deviation methods built-in to any Python libraries to do this! This should be done without importing any additional libraries.

In [2]:
# Code:
def calculate_standard_deviation(numbers):
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / len(numbers)
    standard_deviation = variance ** 0.5
    return standard_deviation

3. Data cleaning function:
    
    Write a function that takes in a string that is a number and a percent symbol (ex. '50%', '30.5%', etc.) and converts this to a float that is the decimal approximation of the percent. For example, inputting '50%' in your function should return 0.5, '30.5%' should return 0.305, etc. Make sure to test your function to make sure it works!

You will use these functions later on in the project!

In [3]:
# Code:
def percent_to_float(percent_string):
    if isinstance(percent_string, float):
        return percent_string
    else:
        float_value = float(percent_string.replace('%', '')) / 100
        return float_value

--- 
# Part 2

Part 2 requires knowledge of Pandas, EDA, data cleaning, and data visualization.

---

*All libraries used should be added here*

In [1]:
# Imports:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

## Data Import and Cleaning

### Data Import & Cleaning

Import the datasets that you selected for this project and go through the following steps at a minimum. You are welcome to do further cleaning as you feel necessary:
1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.
2. Check for missing values.
3. Check for any obvious issues with the observations (keep in mind the minimum & maximum possible values for each test/subtest).
4. Fix any errors you identified in steps 2-3.
5. Display the data types of each feature.
6. Fix any incorrect data types found in step 5.
    - Fix any individual values preventing other columns from being the appropriate type.
    - If your dataset has a column of percents (ex. '50%', '30.5%', etc.), use the function you wrote in Part 1 (coding challenges, number 3) to convert this to floats! *Hint*: use `.map()` or `.apply()`.
7. Rename Columns.
    - Column names should be all lowercase.
    - Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
    - Column names should be unique and informative.
8. Drop unnecessary rows (if needed).
9. Merge dataframes that can be merged.
10. Perform any additional cleaning that you feel is necessary.
11. Save your cleaned and merged dataframes as csv files.

In [2]:
#read SAT dataframe
snap_2018 = pd.read_csv('./data/snap_2018.csv')

#### 1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.

In [3]:
snap_2018.head()

,State,Total number of SNAP households in thousands,Number of SNAP households with children in thousands,Percentage of SNAP households with children,Number of SNAP households with elderly people in thousands,Percentage of SNAP households with elderly people,Number of SNAP households with non-elderly people with disabilities in thousands,Percentage of SNAP households with non-elderly people with disabilities,Number of households with childless adults aged 18-49 without disabilities in thousands,Percentage of SNAP Households with childless adults aged 18-49 without disabilities,Number of SNAP households with earnings in thousands,Percentage of SNAP households with earnings,Number of households with zero gross income in thousands,Percentage of SNAP households with zero gross income,Number of SNAP households with SSI income in thousands,Percentage of SNAP households with SSI income,Number of households with TANF income in thousands,Percentage of SNAP households with TANF income
0,Alabama,354,168,47.6,80,22.7,86.0,24.4,36,10.3,113,31.9,56,15.8,83,23.5,5,1.6
1,Alaska,39,16,41.3,8,21.4,6.0,14.6,9,21.8,11,29.1,11,28.5,6,14.6,3,8.1
2,Arizona,377,175,46.3,80,21.1,55.0,14.5,63,16.7,124,32.8,103,27.4,60,15.8,6,1.6
3,Arkansas,161,78,48.3,30,18.6,53.0,33.0,16,9.8,44,27.1,27,16.7,52,32.5,2,1.4
4,California,1911,940,49.2,325,17.0,51.0,2.7,414,21.7,670,35.1,519,27.1,0,0.0,311,16.3

In [4]:
snap_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 18 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   State                                                                                    53 non-null     object
 1   Total number of SNAP households in thousands                                             53 non-null     int64
 2   Number of SNAP households with children in thousands                                     53 non-null     int64
 3   Percentage of SNAP households with children                                              53 non-null     float64
 4   Number of SNAP households with elderly people in thousands                               53 non-null     int64
 5   Percentage of SNAP households with elderly people                                        53 non-null     float64
 6   Number of SNAP households with non-elderly people with disabilities in thousands         51 non-null     float64
 7   Percentage of SNAP households with non-elderly people with disabilities                  53 non-null     float64
 8   Number of households with childless adults aged 18-49 without disabilities in thousands  53 non-null     int64
 9   Percentage of SNAP Households with childless adults aged 18-49 without disabilities      53 non-null     float64
 10  Number of SNAP households with earnings in thousands                                     53 non-null     int64
 11  Percentage of SNAP households with earnings                                              53 non-null     float64
 12  Number of households with zero gross income in thousands                                 53 non-null     int64
 13  Percentage of SNAP households with zero gross income                                     53 non-null     float64
 14  Number of SNAP households with SSI income in thousands                                   53 non-null     int64
 15  Percentage of SNAP households with SSI income                                            53 non-null     float64
 16  Number of households with TANF income in thousands                                       53 non-null     int64
 17  Percentage of SNAP households with TANF income                                           53 non-null     float64
dtypes: float64(9), int64(8), object(1)
memory usage: 7.6+ KB

#### 2. Check for missing values.

In [5]:
snap_2018.isnull().sum()

State                                                                                      0
Total number of SNAP households in thousands                                               0
Number of SNAP households with children in thousands                                       0
Percentage of SNAP households with children                                                0
Number of SNAP households with elderly people in thousands                                 0
Percentage of SNAP households with elderly people                                          0
Number of SNAP households with non-elderly people with disabilities in thousands           2
Percentage of SNAP households with non-elderly people with disabilities                    0
Number of households with childless adults aged 18-49 without disabilities in thousands    0
Percentage of SNAP Households with childless adults aged 18-49 without disabilities        0
Number of SNAP households with earnings in thousands                                       0
Percentage of SNAP households with earnings                                                0
Number of households with zero gross income in thousands                                   0
Percentage of SNAP households with zero gross income                                       0
Number of SNAP households with SSI income in thousands                                     0
Percentage of SNAP households with SSI income                                              0
Number of households with TANF income in thousands                                         0
Percentage of SNAP households with TANF income                                             0
dtype: int64

#### 3. Check for any obvious issues with the observations (keep in mind the minimum & maximum possible values for each test/subtest).

#### 4. Fix any errors you identified in steps 2-3.

#### 5. Display the data types of each feature.

In [6]:
snap_2018.dtypes

State                                                                                       object
Total number of SNAP households in thousands                                                 int64
Number of SNAP households with children in thousands                                         int64
Percentage of SNAP households with children                                                float64
Number of SNAP households with elderly people in thousands                                   int64
Percentage of SNAP households with elderly people                                          float64
Number of SNAP households with non-elderly people with disabilities in thousands           float64
Percentage of SNAP households with non-elderly people with disabilities                    float64
Number of households with childless adults aged 18-49 without disabilities in thousands      int64
Percentage of SNAP Households with childless adults aged 18-49 without disabilities        float64
Number of SNAP households with earnings in thousands                                         int64
Percentage of SNAP households with earnings                                                float64
Number of households with zero gross income in thousands                                     int64
Percentage of SNAP households with zero gross income                                       float64
Number of SNAP households with SSI income in thousands                                       int64
Percentage of SNAP households with SSI income                                              float64
Number of households with TANF income in thousands                                           int64
Percentage of SNAP households with TANF income                                             float64
dtype: object

#### 6. Fix any incorrect data types found in step 5. 
   - Fix any individual values preventing other columns from being the appropriate type.
   - If your dataset has a column of percents (ex. '50%', '30.5%', etc.), use the function you wrote in Part 1 (coding challenges, number 3) to convert this to floats! 
   - *Hint*: use `.map()` or `.apply()`.

#### 7. Rename Columns.
- Column names should be all lowercase.
- Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
- Column names should be unique and informative.

In [7]:
snap_2018.columns = snap_2018.columns.str.lower()
snap_2018.columns = snap_2018.columns.str.replace(' ', '_')
snap_2018.head(1)

,state,total_number_of_snap_households_in_thousands,number_of_snap_households_with_children_in_thousands,percentage_of_snap_households_with_children,number_of_snap_households_with_elderly_people_in_thousands,percentage_of_snap_households_with_elderly_people,number_of_snap_households_with_non-elderly_people_with_disabilities_in_thousands,percentage_of_snap_households_with_non-elderly_people_with_disabilities,number_of_households_with_childless_adults_aged_18-49_without_disabilities_in_thousands,percentage_of_snap_households_with_childless_adults_aged_18-49_without_disabilities,number_of_snap_households_with_earnings_in_thousands,percentage_of_snap_households_with_earnings,number_of_households_with_zero_gross_income_in_thousands,percentage_of_snap_households_with_zero_gross_income,number_of_snap_households_with_ssi_income_in_thousands,percentage_of_snap_households_with_ssi_income,number_of_households_with_tanf_income_in_thousands,percentage_of_snap_households_with_tanf_income
0,Alabama,354,168,47.6,80,22.7,86.0,24.4,36,10.3,113,31.9,56,15.8,83,23.5,5,1.6

In [8]:
snap_2018.drop(columns=['number_of_snap_households_with_elderly_people_in_thousands',
                       'percentage_of_snap_households_with_elderly_people',
                       'number_of_snap_households_with_non-elderly_people_with_disabilities_in_thousands',
                        'percentage_of_snap_households_with_non-elderly_people_with_disabilities',
                        'number_of_households_with_childless_adults_aged_18-49_without_disabilities_in_thousands',
                        'percentage_of_snap_households_with_childless_adults_aged_18-49_without_disabilities',
                        'number_of_snap_households_with_earnings_in_thousands',
                        'percentage_of_snap_households_with_earnings',
                        'number_of_households_with_zero_gross_income_in_thousands',
                        'percentage_of_snap_households_with_zero_gross_income',
                        'number_of_snap_households_with_ssi_income_in_thousands',
                        'percentage_of_snap_households_with_ssi_income',
                        'number_of_households_with_tanf_income_in_thousands',
                        'percentage_of_snap_households_with_tanf_income'], inplace=True)
snap_2018

,state,total_number_of_snap_households_in_thousands,number_of_snap_households_with_children_in_thousands,percentage_of_snap_households_with_children
0,Alabama,354,168,47.6
1,Alaska,39,16,41.3
2,Arizona,377,175,46.3
3,Arkansas,161,78,48.3
4,California,1911,940,49.2
5,Colorado,219,94,42.8
6,Connecticut,219,69,31.4
7,Delaware,67,29,43.7
8,District of Columbia,68,20,28.9
9,Florida,1632,624,38.3
10,Georgia,699,327,46.8
11,Guam,15,10,63.5
12,Hawaii,82,27,32.7
13,Idaho,69,33,47.3
14,Illinois,904,346,38.3
15,Indiana,270,125,46.3
16,Iowa,161,66,40.7
17,Kansas,99,41,41.4
18,Kentucky,279,113,40.6
19,Louisiana,401,180,44.9
20,Maine,85,28,33.2
21,Maryland,341,127,37.1
22,Massachusetts,447,138,30.9
23,Michigan,672,227,33.8
24,Minnesota,208,80,38.5
25,Mississippi,230,110,47.7
26,Missouri,331,148,44.8
27,Montana,55,21,38.5
28,Nebraska,75,34,46.1
29,Nevada,226,80,35.5
30,New Hampshire,43,18,41.9
31,New Jersey,376,143,38.0
32,New Mexico,214,88,41.1
33,New York,1520,492,32.4
34,North Carolina,634,290,45.8
35,North Dakota,24,10,41.7
36,Ohio,698,281,40.3
37,Oklahoma,260,117,45.2
38,Oregon,358,101,28.2
39,Pennsylvania,946,320,33.9
40,Rhode Island,92,28,30.4
41,South Carolina,301,146,48.3
42,South Dakota,40,18,45.8
43,Tennessee,463,193,41.8
44,Texas,1595,852,53.4
45,Utah,76,39,51.3
46,Vermont,41,12,29.6
47,Virgin Islands,14,6,42.9
48,Virginia,342,154,44.9
49,Washington,495,149,30.0
50,West Virginia,163,61,37.3
51,Wisconsin,323,120,37.2
52,Wyoming,13,6,48.7

In [9]:
# divide the values in the column by 100
snap_2018['percentage_of_snap_households_with_children'] = snap_2018['percentage_of_snap_households_with_children'] / 100

In [10]:
#read SAT dataframe
snap_2019 = pd.read_csv('./data/snap_2019.csv')

#### 1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.

In [11]:
snap_2019.head()

,State,Total number of SNAP households in thousands,Number of SNAP households with children in thousands,Percentage of SNAP households with children,Number of SNAP households with elderly people in thousands,Percentage of SNAP households with elderly people,Number of SNAP households with non-elderly people with disabilities in thousands,Percentage of SNAP households with non-elderly people with disabilities,Number of households with childless adults aged 18-49 without disabilities in thousands,Percentage of SNAP Households with childless adults aged 18-49 without disabilities,Number of SNAP households with earnings in thousands,Percentage of SNAP households with earnings,Number of households with zero gross income in thousands,Percentage of SNAP households with zero gross income,Number of SNAP households with SSI income in thousands,Percentage of SNAP households with SSI income,Number of households with TANF income in thousands,Percentage of SNAP households with TANF income
0,Alabama,354,168,47.6,80,22.7,86.0,24.4,36,10.3,113,31.9,56,15.8,83,23.5,5,1.6
1,Alaska,39,16,41.3,8,21.4,6.0,14.6,9,21.8,11,29.1,11,28.5,6,14.6,3,8.1
2,Arizona,377,175,46.3,80,21.1,55.0,14.5,63,16.7,124,32.8,103,27.4,60,15.8,6,1.6
3,Arkansas,161,78,48.3,30,18.6,53.0,33.0,16,9.8,44,27.1,27,16.7,52,32.5,2,1.4
4,California,1911,940,49.2,325,17.0,51.0,2.7,414,21.7,670,35.1,519,27.1,0,0.0,311,16.3

In [12]:
snap_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 18 columns):
 #   Column                                                                                   Non-Null Count  Dtype
---  ------                                                                                   --------------  -----
 0   State                                                                                    53 non-null     object
 1   Total number of SNAP households in thousands                                             53 non-null     int64
 2   Number of SNAP households with children in thousands                                     53 non-null     int64
 3   Percentage of SNAP households with children                                              53 non-null     float64
 4   Number of SNAP households with elderly people in thousands                               53 non-null     int64
 5   Percentage of SNAP households with elderly people                                        53 non-null     float64
 6   Number of SNAP households with non-elderly people with disabilities in thousands         51 non-null     float64
 7   Percentage of SNAP households with non-elderly people with disabilities                  53 non-null     float64
 8   Number of households with childless adults aged 18-49 without disabilities in thousands  53 non-null     int64
 9   Percentage of SNAP Households with childless adults aged 18-49 without disabilities      53 non-null     float64
 10  Number of SNAP households with earnings in thousands                                     53 non-null     int64
 11  Percentage of SNAP households with earnings                                              53 non-null     float64
 12  Number of households with zero gross income in thousands                                 53 non-null     int64
 13  Percentage of SNAP households with zero gross income                                     53 non-null     float64
 14  Number of SNAP households with SSI income in thousands                                   53 non-null     int64
 15  Percentage of SNAP households with SSI income                                            53 non-null     float64
 16  Number of households with TANF income in thousands                                       53 non-null     int64
 17  Percentage of SNAP households with TANF income                                           53 non-null     float64
dtypes: float64(9), int64(8), object(1)
memory usage: 7.6+ KB

#### 2. Check for missing values.

In [13]:
snap_2019.isnull().sum()

State                                                                                      0
Total number of SNAP households in thousands                                               0
Number of SNAP households with children in thousands                                       0
Percentage of SNAP households with children                                                0
Number of SNAP households with elderly people in thousands                                 0
Percentage of SNAP households with elderly people                                          0
Number of SNAP households with non-elderly people with disabilities in thousands           2
Percentage of SNAP households with non-elderly people with disabilities                    0
Number of households with childless adults aged 18-49 without disabilities in thousands    0
Percentage of SNAP Households with childless adults aged 18-49 without disabilities        0
Number of SNAP households with earnings in thousands                                       0
Percentage of SNAP households with earnings                                                0
Number of households with zero gross income in thousands                                   0
Percentage of SNAP households with zero gross income                                       0
Number of SNAP households with SSI income in thousands                                     0
Percentage of SNAP households with SSI income                                              0
Number of households with TANF income in thousands                                         0
Percentage of SNAP households with TANF income                                             0
dtype: int64

#### 3. Check for any obvious issues with the observations (keep in mind the minimum & maximum possible values for each test/subtest).

#### 4. Fix any errors you identified in steps 2-3.

#### 5. Display the data types of each feature.

In [14]:
snap_2019.dtypes

State                                                                                       object
Total number of SNAP households in thousands                                                 int64
Number of SNAP households with children in thousands                                         int64
Percentage of SNAP households with children                                                float64
Number of SNAP households with elderly people in thousands                                   int64
Percentage of SNAP households with elderly people                                          float64
Number of SNAP households with non-elderly people with disabilities in thousands           float64
Percentage of SNAP households with non-elderly people with disabilities                    float64
Number of households with childless adults aged 18-49 without disabilities in thousands      int64
Percentage of SNAP Households with childless adults aged 18-49 without disabilities        float64
Number of SNAP households with earnings in thousands                                         int64
Percentage of SNAP households with earnings                                                float64
Number of households with zero gross income in thousands                                     int64
Percentage of SNAP households with zero gross income                                       float64
Number of SNAP households with SSI income in thousands                                       int64
Percentage of SNAP households with SSI income                                              float64
Number of households with TANF income in thousands                                           int64
Percentage of SNAP households with TANF income                                             float64
dtype: object

#### 6. Fix any incorrect data types found in step 5. 
   - Fix any individual values preventing other columns from being the appropriate type.
   - If your dataset has a column of percents (ex. '50%', '30.5%', etc.), use the function you wrote in Part 1 (coding challenges, number 3) to convert this to floats! 
   - *Hint*: use `.map()` or `.apply()`.

#### 7. Rename Columns.
- Column names should be all lowercase.
- Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
- Column names should be unique and informative.

In [15]:
snap_2019.columns = snap_2019.columns.str.lower()
snap_2019.columns = snap_2019.columns.str.replace(' ', '_')
snap_2019.head(1)

,state,total_number_of_snap_households_in_thousands,number_of_snap_households_with_children_in_thousands,percentage_of_snap_households_with_children,number_of_snap_households_with_elderly_people_in_thousands,percentage_of_snap_households_with_elderly_people,number_of_snap_households_with_non-elderly_people_with_disabilities_in_thousands,percentage_of_snap_households_with_non-elderly_people_with_disabilities,number_of_households_with_childless_adults_aged_18-49_without_disabilities_in_thousands,percentage_of_snap_households_with_childless_adults_aged_18-49_without_disabilities,number_of_snap_households_with_earnings_in_thousands,percentage_of_snap_households_with_earnings,number_of_households_with_zero_gross_income_in_thousands,percentage_of_snap_households_with_zero_gross_income,number_of_snap_households_with_ssi_income_in_thousands,percentage_of_snap_households_with_ssi_income,number_of_households_with_tanf_income_in_thousands,percentage_of_snap_households_with_tanf_income
0,Alabama,354,168,47.6,80,22.7,86.0,24.4,36,10.3,113,31.9,56,15.8,83,23.5,5,1.6

#### 8. Drop unnecessary rows (if needed).

In [16]:
snap_2019.drop(columns=['number_of_snap_households_with_elderly_people_in_thousands',
                       'percentage_of_snap_households_with_elderly_people',
                       'number_of_snap_households_with_non-elderly_people_with_disabilities_in_thousands',
                        'percentage_of_snap_households_with_non-elderly_people_with_disabilities',
                        'number_of_households_with_childless_adults_aged_18-49_without_disabilities_in_thousands',
                        'percentage_of_snap_households_with_childless_adults_aged_18-49_without_disabilities',
                        'number_of_snap_households_with_earnings_in_thousands',
                        'percentage_of_snap_households_with_earnings',
                        'number_of_households_with_zero_gross_income_in_thousands',
                        'percentage_of_snap_households_with_zero_gross_income',
                        'number_of_snap_households_with_ssi_income_in_thousands',
                        'percentage_of_snap_households_with_ssi_income',
                        'number_of_households_with_tanf_income_in_thousands',
                        'percentage_of_snap_households_with_tanf_income'], inplace=True)
snap_2019

,state,total_number_of_snap_households_in_thousands,number_of_snap_households_with_children_in_thousands,percentage_of_snap_households_with_children
0,Alabama,354,168,47.6
1,Alaska,39,16,41.3
2,Arizona,377,175,46.3
3,Arkansas,161,78,48.3
4,California,1911,940,49.2
5,Colorado,219,94,42.8
6,Connecticut,219,69,31.4
7,Delaware,67,29,43.7
8,District of Columbia,68,20,28.9
9,Florida,1632,624,38.3
10,Georgia,699,327,46.8
11,Guam,15,10,63.5
12,Hawaii,82,27,32.7
13,Idaho,69,33,47.3
14,Illinois,904,346,38.3
15,Indiana,270,125,46.3
16,Iowa,161,66,40.7
17,Kansas,99,41,41.4
18,Kentucky,279,113,40.6
19,Louisiana,401,180,44.9
20,Maine,85,28,33.2
21,Maryland,341,127,37.1
22,Massachusetts,447,138,30.9
23,Michigan,672,227,33.8
24,Minnesota,208,80,38.5
25,Mississippi,230,110,47.7
26,Missouri,331,148,44.8
27,Montana,55,21,38.5
28,Nebraska,75,34,46.1
29,Nevada,226,80,35.5
30,New Hampshire,43,18,41.9
31,New Jersey,376,143,38.0
32,New Mexico,214,88,41.1
33,New York,1520,492,32.4
34,North Carolina,634,290,45.8
35,North Dakota,24,10,41.7
36,Ohio,698,281,40.3
37,Oklahoma,260,117,45.2
38,Oregon,358,101,28.2
39,Pennsylvania,946,320,33.9
40,Rhode Island,92,28,30.4
41,South Carolina,301,146,48.3
42,South Dakota,40,18,45.8
43,Tennessee,463,193,41.8
44,Texas,1595,852,53.4
45,Utah,76,39,51.3
46,Vermont,41,12,29.6
47,Virgin Islands,14,6,42.9
48,Virginia,342,154,44.9
49,Washington,495,149,30.0
50,West Virginia,163,61,37.3
51,Wisconsin,323,120,37.2
52,Wyoming,13,6,48.7

In [17]:
snap_2019['percentage_of_snap_households_with_children'] = snap_2019['percentage_of_snap_households_with_children'] / 100

#### 9. Merge dataframes that can be merged.

In [18]:
snap_2018_2019 = pd.merge(snap_2018,snap_2019, on = 'state',suffixes=('_2018', '_2019'))
snap_2018_2019

,state,total_number_of_snap_households_in_thousands_2018,number_of_snap_households_with_children_in_thousands_2018,percentage_of_snap_households_with_children_2018,total_number_of_snap_households_in_thousands_2019,number_of_snap_households_with_children_in_thousands_2019,percentage_of_snap_households_with_children_2019
0,Alabama,354,168,0.476,354,168,0.476
1,Alaska,39,16,0.413,39,16,0.413
2,Arizona,377,175,0.463,377,175,0.463
3,Arkansas,161,78,0.483,161,78,0.483
4,California,1911,940,0.492,1911,940,0.492
5,Colorado,219,94,0.428,219,94,0.428
6,Connecticut,219,69,0.314,219,69,0.314
7,Delaware,67,29,0.437,67,29,0.437
8,District of Columbia,68,20,0.289,68,20,0.289
9,Florida,1632,624,0.383,1632,624,0.383
10,Georgia,699,327,0.468,699,327,0.468
11,Guam,15,10,0.635,15,10,0.635
12,Hawaii,82,27,0.327,82,27,0.327
13,Idaho,69,33,0.473,69,33,0.473
14,Illinois,904,346,0.383,904,346,0.383
15,Indiana,270,125,0.463,270,125,0.463
16,Iowa,161,66,0.407,161,66,0.407
17,Kansas,99,41,0.414,99,41,0.414
18,Kentucky,279,113,0.406,279,113,0.406
19,Louisiana,401,180,0.449,401,180,0.449
20,Maine,85,28,0.332,85,28,0.332
21,Maryland,341,127,0.371,341,127,0.371
22,Massachusetts,447,138,0.309,447,138,0.309
23,Michigan,672,227,0.338,672,227,0.338
24,Minnesota,208,80,0.385,208,80,0.385
25,Mississippi,230,110,0.477,230,110,0.477
26,Missouri,331,148,0.448,331,148,0.448
27,Montana,55,21,0.385,55,21,0.385
28,Nebraska,75,34,0.461,75,34,0.461
29,Nevada,226,80,0.355,226,80,0.355
30,New Hampshire,43,18,0.419,43,18,0.419
31,New Jersey,376,143,0.380,376,143,0.380
32,New Mexico,214,88,0.411,214,88,0.411
33,New York,1520,492,0.324,1520,492,0.324
34,North Carolina,634,290,0.458,634,290,0.458
35,North Dakota,24,10,0.417,24,10,0.417
36,Ohio,698,281,0.403,698,281,0.403
37,Oklahoma,260,117,0.452,260,117,0.452
38,Oregon,358,101,0.282,358,101,0.282
39,Pennsylvania,946,320,0.339,946,320,0.339
40,Rhode Island,92,28,0.304,92,28,0.304
41,South Carolina,301,146,0.483,301,146,0.483
42,South Dakota,40,18,0.458,40,18,0.458
43,Tennessee,463,193,0.418,463,193,0.418
44,Texas,1595,852,0.534,1595,852,0.534
45,Utah,76,39,0.513,76,39,0.513
46,Vermont,41,12,0.296,41,12,0.296
47,Virgin Islands,14,6,0.429,14,6,0.429
48,Virginia,342,154,0.449,342,154,0.449
49,Washington,495,149,0.300,495,149,0.300
50,West Virginia,163,61,0.373,163,61,0.373
51,Wisconsin,323,120,0.372,323,120,0.372
52,Wyoming,13,6,0.487,13,6,0.487

In [19]:
snap_2018_2019.to_csv('./data/snap_2018_2019.csv', index = False)

In [20]:
sat = pd.read_csv('./data/sat_merged.csv')

In [21]:
sat_snap = pd.merge(sat, snap_2018_2019, on = 'state')
sat_snap.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51 entries, 0 to 50
Data columns (total 11 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   state                                                      51 non-null     object
 1   participation_rate_2018                                    51 non-null     float64
 2   total_score_2018                                           51 non-null     int64
 3   participation_rate_2019                                    51 non-null     float64
 4   total_score_2019                                           51 non-null     int64
 5   total_number_of_snap_households_in_thousands_2018          51 non-null     int64
 6   number_of_snap_households_with_children_in_thousands_2018  51 non-null     int64
 7   percentage_of_snap_households_with_children_2018           51 non-null     float64
 8   total_number_of_snap_households_in_thousands_2019          51 non-null     int64
 9   number_of_snap_households_with_children_in_thousands_2019  51 non-null     int64
 10  percentage_of_snap_households_with_children_2019           51 non-null     float64
dtypes: float64(4), int64(6), object(1)
memory usage: 4.8+ KB

#### 10. Perform any additional cleaning that you feel is necessary.

#### 11. Save your cleaned and merged dataframes as csv files.

In [22]:
sat_snap.to_csv('./data/sat_snap_2018_2019.csv', index = False)

In [23]:
df = pd.read_csv('./data/sat_snap_2018_2019.csv')

In [24]:
df.head()

,state,participation_rate_2018,total_score_2018,participation_rate_2019,total_score_2019,total_number_of_snap_households_in_thousands_2018,number_of_snap_households_with_children_in_thousands_2018,percentage_of_snap_households_with_children_2018,total_number_of_snap_households_in_thousands_2019,number_of_snap_households_with_children_in_thousands_2019,percentage_of_snap_households_with_children_2019
0,Alabama,0.06,1166,0.07,1143,354,168,0.476,354,168,0.476
1,Alaska,0.43,1106,0.41,1097,39,16,0.413,39,16,0.413
2,Arizona,0.29,1149,0.31,1134,377,175,0.463,377,175,0.463
3,Arkansas,0.05,1169,0.06,1141,161,78,0.483,161,78,0.483
4,California,0.60,1076,0.63,1065,1911,940,0.492,1911,940,0.492